language: php
sudo: false
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 5.3
      dist: precise
      sudo: true

install:
  - travis_retry composer self-update
  - travis_retry composer install
  - phpenv rehash

script:
  - ./vendor/bin/phpunit --coverage-text
